[package]
name = "pugl-sys"
version = "0.1.0"
authors = ["Johannes Mueller <github@johannes-mueller.org>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
cairo-rs = "0.8.1"
cairo-sys-rs = "0.9.2"

[build-dependencies]
bindgen = "0.53.2"
